version: "3"
services:
  taxfrauders:
    build: .
    image: taxfrauders:latest
    ports: 
      - "8080:8080"
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
        - '6650:3306'
    environment:
        MYSQL_ROOT_PASSWORD: 'taxfrauders'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: 'taxfrauders'
    volumes:
        - './database:/var/lib/mysql'